name: tumble
version: '0.0.1.0-SNAPSHOT'
main: net.lahan.tumble.Tumble
api-version: '1.21'
authors: [ atlanticbomber ]
description: Tumble minigame from the xbox360 edition
commands:
  snowDestroysBlocks:
    description: Allows snowballs to break blocks they hit
    aliases: [snowBreaks, snowTime]
    usage: "Usage: /snowDestroysBlocks [true|false]"
  arena:
    description: Allows users to set the area in which tumble mechanics function, set the default arena size for games, and disable the arena (set, size, and disable respectively)
    usage: "Usage: /arena set [int| ] [int| ] [int| ] [int| ], size [int|default], disable"
